title: useless ulysses
description: 法哲学片断与学术之路
show_downloads: false
permalink: /:title:output_ext
timezone: Asia/Shanghai
author: Ulysses
google_analytics: 
theme: jekyll-theme-tactile
baseurl:
url: https:/uselessulysses.com
incremental: true
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll/tagging
  - jekyll-tagging-related_posts
sass:
    style: compressed
paginate: 10
paginate_path: "/page/:num"

algolia:
  application_id: 9872TK5O1S
  index_name: Vercel
  search_only_api_key: cb96ceb3b9b2662dc26d1fd67ff62534
  

