title: Pathos Page
description: 法哲学片断与学术之路
show_downloads: false
permalink: /:title:output_ext
timezone: Asia/Shanghai
author: Pathos Page
google_analytics: 
theme: jekyll-theme-tactile
baseurl:
url: https://pathos.page
incremental: true
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll/tagging
  - jekyll-tagging-related_posts
sass:
    style: compressed
paginate: 10
paginate_path: "/page/:num"

algolia:
  application_id: LMLNNI8SR9
  index_name: pathos_vercel
  search_only_api_key: 7d021be1658da99c0eddbaaffcbbcf69


